# Generated by Django 4.1.7 on 2023-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicksapp', '0003_alter_adminusr_weapon_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorydata',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
