# Generated by Django 4.1.7 on 2023-03-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wicksapp', '0004_alter_armorydata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorydata',
            name='weapon_img',
            field=models.ImageField(blank=True, null=True, upload_to='admin_conf_data/'),
        ),
        migrations.CreateModel(
            name='heronWicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(max_length=40)),
                ('lead_img', models.ImageField(blank=True, null=True, upload_to='Wicks_heron')),
                ('lead_desc', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wicksapp.adminusr')),
            ],
        ),
    ]
