# Generated by Django 4.1.7 on 2023-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicksapp', '0005_alter_armorydata_weapon_img_heronwicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='heronwicks',
            name='date_time',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='heronwicks',
            name='lead_img',
            field=models.ImageField(blank=True, null=True, upload_to='Wicks_heron/'),
        ),
    ]
