# Generated by Django 4.1.7 on 2023-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicksapp', '0006_heronwicks_date_time_alter_heronwicks_lead_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='mission_backgrounds/')),
                ('audio_file', models.FileField(upload_to='mission_audio/')),
            ],
        ),
    ]
